# Generated by Django 3.0.5 on 2021-01-16 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('rating', models.CharField(default='', max_length=100)),
                ('avatar', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
