# Generated by Django 3.0.5 on 2021-01-16 17:34

import carts.models
import datetime
from django.db import migrations, models
import djongo.models.fields
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=100)),
                ('address1', models.TextField(default='')),
                ('address2', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=100)),
                ('postcode', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('productId', models.IntegerField()),
                ('variationId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('taxClass', models.CharField(default='', max_length=100)),
                ('subtotal', models.CharField(default='', max_length=100)),
                ('subtotalTax', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('totalTax', models.CharField(default='', max_length=100)),
                ('taxes', models.CharField(default='', max_length=100)),
                ('sku', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('number', models.CharField(default='', max_length=100)),
                ('orderKey', models.CharField(default='', max_length=100)),
                ('createdVia', models.CharField(default='', max_length=100)),
                ('version', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=100)),
                ('dateCreated', models.DateTimeField()),
                ('dateModified', models.DateTimeField()),
                ('discountTotal', models.CharField(default='', max_length=100)),
                ('shippingTotal', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('totalTax', models.CharField(default='', max_length=100)),
                ('billing', djongo.models.fields.EmbeddedField(model_container=orders.models.Address)),
                ('shipping', djongo.models.fields.EmbeddedField(model_container=orders.models.Address)),
                ('datePaid', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dateCompleted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cartHash', models.CharField(default='', max_length=100)),
                ('lineItems', djongo.models.fields.ArrayField(model_container=orders.models.LineItem)),
                ('shippingLines', djongo.models.fields.ArrayField(model_container=orders.models.ShippingLine)),
                ('customerUID', models.CharField(max_length=100)),
                ('cartModel', djongo.models.fields.EmbeddedField(model_container=carts.models.CartModel)),
                ('decimals', models.IntegerField()),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.CharField(max_length=100)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingLine',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('methodTitle', models.CharField(default='', max_length=100)),
                ('methodId', models.CharField(default='', max_length=100)),
                ('instanceId', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('totalTax', models.CharField(default='', max_length=100)),
                ('taxes', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
