# Generated by Django 3.0.5 on 2021-01-16 17:34

import carts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartContent',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=100)),
                ('productId', models.IntegerField()),
                ('variationId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('thumb', models.CharField(default='', max_length=100)),
                ('formattedPrice', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CartFee',
            fields=[
                ('p', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('_id', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('cartContents', djongo.models.fields.ArrayField(model_container=carts.models.CartContent)),
                ('cartNonce', models.CharField(default='', max_length=100)),
                ('cartTotals', djongo.models.fields.EmbeddedField(model_container=carts.models.CartTotals)),
                ('currency', models.CharField(default='INR', max_length=100)),
                ('cartFees', djongo.models.fields.ArrayField(model_container=carts.models.CartFee)),
            ],
        ),
        migrations.CreateModel(
            name='CartTotals',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField(default='', max_length=100)),
                ('shippingTotal', models.CharField(default='', max_length=100)),
                ('discountTotal', models.IntegerField(default='', max_length=100)),
                ('total', models.IntegerField(default='', max_length=100)),
                ('totalTax', models.IntegerField(default='', max_length=100)),
            ],
        ),
    ]
