# Generated by Django 3.0.4 on 2020-12-19 13:13

import customers.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('billing', djongo.models.fields.EmbeddedField(model_container=customers.models.Address)),
                ('shipping', djongo.models.fields.EmbeddedField(model_container=customers.models.Address)),
                ('isPayingCustomer', models.BooleanField()),
                ('ordersCount', models.IntegerField()),
                ('totalSpent', models.CharField(max_length=100)),
                ('avatarUrl', models.CharField(max_length=255)),
                ('guest', models.CharField(max_length=100)),
            ],
        ),
    ]
