# Generated by Django 3.0.5 on 2021-01-16 17:34

import datetime
from django.db import migrations, models
import djongo.models.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('position', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('variation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailableVariation',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('dimensions', djongo.models.fields.EmbeddedField(model_container=products.models.Dimensions)),
                ('displayPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('displayRegularPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', djongo.models.fields.EmbeddedField(model_container=products.models.AvailableVariationImage)),
                ('isInStock', models.BooleanField()),
                ('isPurchasable', models.BooleanField()),
                ('sku', models.CharField(default='', max_length=100)),
                ('variationDescription', models.CharField(default='', max_length=100)),
                ('variationId', models.IntegerField()),
                ('option', djongo.models.fields.ArrayField(model_container=products.models.Option)),
                ('formattedPrice', models.CharField(default='', max_length=100)),
                ('formattedSalesPrice', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableVariationImage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('href', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAttribute',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('length', models.CharField(default='', max_length=100)),
                ('width', models.CharField(default='', max_length=100)),
                ('height', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('_self', djongo.models.fields.ArrayField(model_container=products.models.Collection)),
                ('collection', djongo.models.fields.ArrayField(model_container=products.models.Collection)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('key', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100)),
                ('permalink', models.CharField(default='', max_length=100)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dateModified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type1', models.CharField(default='variable', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('shortDescription', models.TextField(default='')),
                ('sku', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('regularPrice', models.CharField(default='', max_length=100)),
                ('salePrice', models.CharField(default='', max_length=100)),
                ('onSale', models.BooleanField(default=False)),
                ('totalSales', models.IntegerField()),
                ('externalUrl', models.CharField(default='', max_length=100)),
                ('buttonText', models.CharField(default='', max_length=100)),
                ('taxStatus', models.CharField(default='', max_length=100)),
                ('stockQuantity', models.IntegerField()),
                ('stockStatus', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('dimensions', djongo.models.fields.EmbeddedField(model_container=products.models.Dimensions)),
                ('shippingRequired', models.BooleanField()),
                ('reviewsAllowed', models.BooleanField()),
                ('averageRating', models.CharField(default='', max_length=100)),
                ('ratingCount', models.IntegerField()),
                ('images', djongo.models.fields.ArrayField(model_container=products.models.ProductImage)),
                ('availableVariations', djongo.models.fields.ArrayField(model_container=products.models.AvailableVariation)),
                ('vendor', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('productId', models.CharField(max_length=100)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dateModified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('src', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('attribute', models.CharField(default='', max_length=100)),
                ('selected', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
